[versions]
agp = "8.2.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"

deviceSdk = "v1.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
hwoh-device-connect-service = { module = "com.github.felixcc:hwoh-device-connect-service", version.ref = "deviceSdk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
